/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import javax.swing.JOptionPane;

/**
 *
 * @author Alessandro Fazio
 */
public class EstudiantesView extends javax.swing.JFrame {

    /**
     * Creates new form Estudiantes
     */
    public EstudiantesView() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_crearEstudiante = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_estudiantes = new javax.swing.JTable();
        jb_crearEstudiante = new javax.swing.JButton();
        jb_actualizarEstudiante = new javax.swing.JButton();
        jb_eliminarEstudiante = new javax.swing.JButton();

        javax.swing.GroupLayout jd_crearEstudianteLayout = new javax.swing.GroupLayout(jd_crearEstudiante.getContentPane());
        jd_crearEstudiante.getContentPane().setLayout(jd_crearEstudianteLayout);
        jd_crearEstudianteLayout.setHorizontalGroup(
            jd_crearEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 657, Short.MAX_VALUE)
        );
        jd_crearEstudianteLayout.setVerticalGroup(
            jd_crearEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 437, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jt_estudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Cedula", "Nombre", "Teléfono", "Email", "Fecha de nacimiento", "Carrera"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jt_estudiantes);

        jb_crearEstudiante.setText("Crear estudiante");
        jb_crearEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_crearEstudianteActionPerformed(evt);
            }
        });

        jb_actualizarEstudiante.setText("Actualizar estudiante");
        jb_actualizarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_actualizarEstudianteActionPerformed(evt);
            }
        });

        jb_eliminarEstudiante.setText("Eliminar estudiante");
        jb_eliminarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_eliminarEstudianteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jb_crearEstudiante)
                .addGap(218, 218, 218)
                .addComponent(jb_actualizarEstudiante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
                .addComponent(jb_eliminarEstudiante)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_crearEstudiante)
                    .addComponent(jb_eliminarEstudiante)
                    .addComponent(jb_actualizarEstudiante))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_crearEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_crearEstudianteActionPerformed
        jd_crearEstudiante.setVisible(true);
    }//GEN-LAST:event_jb_crearEstudianteActionPerformed

    private void jb_actualizarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_actualizarEstudianteActionPerformed
        jd_crearEstudiante.setVisible(true);
    }//GEN-LAST:event_jb_actualizarEstudianteActionPerformed

    private void jb_eliminarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_eliminarEstudianteActionPerformed
        jd_crearEstudiante.setVisible(true);
    }//GEN-LAST:event_jb_eliminarEstudianteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_actualizarEstudiante;
    private javax.swing.JButton jb_crearEstudiante;
    private javax.swing.JButton jb_eliminarEstudiante;
    private javax.swing.JDialog jd_crearEstudiante;
    private javax.swing.JTable jt_estudiantes;
    // End of variables declaration//GEN-END:variables
}
